synthetic-package: false
arb-dir: lib/src/core/src/l10n/translates
output-dir: lib/src/core/src/l10n/generate
template-arb-file: app_ru.arb
output-localization-file: app_localizations.dart
nullable-getter: false